# StatefulSet for mail core service
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mailman-core
  namespace: mail
  labels:
    app: mail-suit-service
    component: mail-core-service
spec:
  serviceName: mail-suit-service
  replicas: 1
  selector:
    matchLabels:
      app: mail-suit-service
      component: mail-core-service
  template:
    metadata:
      labels:
        app: mail-suit-service
        component: mail-core-service
    spec:
      containers:
        - name: mailman-core
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail-core:v0.1.1
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman/
              name: mailman-core-volume
            - mountPath: /usr/lib/python3.6/site-packages/mailman/runners/command.py
              name: mailman-core-hack-volume
              subPath: command.py
          env:
            - name: DATABASE_TYPE
              value: mysql
            - name: DATABASE_CLASS
              value: mailman.database.mysql.MySQLDatabase
            - name: MAILMAN_REST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_user
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_password
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: hyperkitty_api_key
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mysql_password
            - name: HYPERKITTY_URL
            # NOTE: Please update the HYPERKITTY_URL
              value: http://mailman-web-service.mail.svc.cluster.local/hyperkitty
            - name: SMTP_HOST
              value: mailman-exim4-service.mail.svc.cluster.local
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_username
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_password
          # Sed command is used here to force change default charsets to UTF-8
          # related issue: https://gitlab.com/mailman/postorius/issues/325
          command:
            - /bin/sh
            - -c
            - |
              export DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@192.168.1.3:3306/mailman
              sed -i "s/charset: us-ascii/charset: utf-8/g" /usr/lib/python3.6/site-packages/mailman/config/schema.cfg;
              sed -i "s/email_commands_max_lines: 10/email_commands_max_lines: 30/g" /usr/lib/python3.6/site-packages/mailman/config/schema.cfg;
              exec docker-entrypoint.sh master --force
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
      volumes:
        - name: mailman-core-volume
          persistentVolumeClaim:
            claimName: config-vol
        - name: mailman-core-hack-volume
          configMap:
            name: mailman-webpage-hack
