---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/infra-common/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/infra-common/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/infra-common/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/infra-common/mail_secrets
      key: secret_key
    mysql_user:
      path: secrets/data/infra-common/mail_secrets
      key: mysql_user
    mysql_password:
      path: secrets/data/infra-common/mail_secrets
      key: mysql_password
    mailman_admin_email:
      path: secrets/data/infra-common/mail_secrets
      key: mailman_admin_email
    exim4_credential:
      path: secrets/data/infra-common/mail_secrets
      key: exim4_credential
    exim4_credential_username:
      path: secrets/data/infra-common/mail_secrets
      key: exim4_credential_splitted_username
    exim4_credential_password:
      path: secrets/data/infra-common/mail_secrets
      key: exim4_credential_splitted_password
    dkim_key:
      path: secrets/data/infra-common/mail_secrets
      key: dkim_key

# secret for osinfra org domain
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets
  namespace: mail
spec:
  name: mailman-cert-secrets
  keysMap:
    server_crt:
      path: secrets/data/infra-common/osinfra
      key: tls.cert
    server_key:
      path: secrets/data/infra-common/osinfra
      key: tls.key
    ca.crt:
      path: secrets/data/infra-common/osinfra
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-common/osinfra
      key: tls.cert
    tls.key:
      path: secrets/data/infra-common/osinfra
      key: tls.key
# secret for openhetuengine org domain
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-cert-secrets-foropenhetu
  namespace: mail
spec:
  name: mailman-cert-secrets-foropenhetu
  keysMap:
    server_crt:
      path: secrets/data/infra-common/mail_secrets
      key: hetu_tls.cert
    server_key:
      path: secrets/data/infra-common/mail_secrets
      key: hetu_tls.key
    ca.crt:
      path: secrets/data/infra-common/mail_secrets
      key: hetu_tls.cert
    tls.crt:
      path: secrets/data/infra-common/mail_secrets
      key: hetu_tls.cert
    tls.key:
      path: secrets/data/infra-common/mail_secrets
      key: hetu_tls.key
