apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: om-secrets
spec:
  name: account-org-om-secrets
  keysMap:
    credentials_cfg:
      path: secrets/data/mindspore/om
      key: mindspore_account_org_credentials.cfg
    email_userid:
      path: secrets/data/mindspore/om
      key: email_userid.csv
