---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: cla-secrets
spec:
  name: cla-secrets
  keysMap:
    api-token-key:
      path: secrets/data/infra-common/cla
      key: api-token-key
    code-platforms:
      path: secrets/data/infra-common/cla
      key: code-platforms
    email:
      path: secrets/data/infra-common/cla
      key: email
    gmail:
      path: secrets/data/infra-common/cla
      key: gmail
    mongodb-connection:
      path: secrets/data/infra-common/cla
      key: mongodb-connection
    symmetric-encryption-key:
      path: secrets/data/infra-common/cla
      key: symmetric-encryption-key
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: tls-secrets
spec:
  name: tls-secrets
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/cla
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-common/cla
      key: tls.cert
    tls.key:
      path: secrets/data/infra-common/cla
      key: tls.key
