kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  log-format-escape-json: "true"
  log-format-upstream: '{"time": "$time_iso8601", "proxy_remote_addr": "$proxy_protocol_addr", "remote_addr": "$remote_addr", "http_range": "$http_range", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
    "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status, "vhost": "$host", "request_proto": "$server_protocol",
    "path": "$uri", "request_query": "$args", "request_length": "$request_length", "duration": "$upstream_response_time", "upstream_status": "$upstream_status", "method": "$request_method", "http_referrer": "$http_referer",
    "http_user_agent": "$http_user_agent", "geoip2_city_country_name": "$geoip2_city_country_name", "geoip2_city": "$geoip2_city",
    "geoip2_latitude": "$geoip2_latitude", "geoip2_longitude": "$geoip2_longitude", "upstream_addr": "$upstream_addr"}'
  use-geoip2: "true"
  server-tokens: "false"
  proxy-connect-timeout: "70"
  keep-alive: "10"
  client-body-buffer-size: "64k"
  add-headers: "ingress-nginx/custom-headers"
  http-snippet: |
    proxy_cache_path /tmp/statics_cache levels=1:2 keys_zone=statics_cache:50m use_temp_path=off max_size=500m inactive=1h;
    map $http_x_requested_with $nocache {
        default 0;
        XMLHttpRequest 1;
    }
