# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sca-dm
  namespace: sca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sca-dm
  template:
    metadata:
      labels:
        app: sca-dm
    spec:
      imagePullSecrets:
        - name: sca-sec
      containers:
      - name: sca-dm
        image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/sca-datamanager:6a082c8dc57e59acb2e8d7b6b1b37d916559ec3c
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 7979
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_NAME
            value: dm-service
          - name: EUREKA_SERVER
            value: "http://eureka-0.eureka:9000/eureka, http://eureka-1.eureka:9000/eureka"
          - name: APP_ENV
            value: prod
          - name: PACKAGE_VERSION
            value: 1.0-SNAPSHOT
          - name: MAX_HEAP_MEM
            value: 3072m
          - name: INIT_HEAP_MEM
            value: 1024m
          - name: CMS_IOF
            value: "75"
          - name: INIT_KEY
            valueFrom:
              secretKeyRef:
                name: sca-secret
                key: app-init-key
        resources:
          requests:
            cpu: 200m
            memory: 2G
          limits:
            cpu: 2000m
            memory: 4G
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: sca-dm
  namespace: sca
  labels:
    app: sca-dm
spec:
  type: ClusterIP
  ports:
    - port: 7979
      protocol: TCP
      name: dm-app
      targetPort: 7979
  selector:
    app: sca-dm
