---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: sca
  labels:
    app: eureka
spec:
  type: ClusterIP
  ports:
    - port: 9000
      name: eureka
      targetPort: 9000
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: sca
spec:
  replicas: 2
  serviceName: "eureka"
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      imagePullSecrets:
        - name: sca-sec
      containers:
        - name: eureka
          image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/sca-eureka:2da74f4f19e420bdc7233954881e632c1c57eae0
          ports:
            - containerPort: 9000
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_SERVER
              value: "http://eureka-0.eureka:9000/eureka, http://eureka-1.eureka:9000/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka
            - name: SERVICE_NAME
              value: sca-eureka
            - name: APP_ENV
              value: prod
            - name: PACKAGE_VERSION
              value: 1.0-SNAPSHOT
            - name: MAX_HEAP_MEM
              value: 512m
            - name: INIT_HEAP_MEM
              value: 256m
            - name: CMS_IOF
              value: "75"
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 600Mi
