---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    spec:
      containers:
        - name: jenkins
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: osinfra-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: osinfra-jenkins
      initContainers:
        - name: copy-default-config
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins"
            - name: JENKINS_UC
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: osinfra-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: osinfra-jenkins
          # NOTE(tommylikehu): Copy config file not working when jenkins upgraded, disable it here via command overwrite.
          command:
            - /bin/sh
            - -c
            - |
              sleep 1;
